project:
  type: website

website:
  title: "My Blog: Sean McKeown and the LLMS/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css

execute:
  freeze: auto



